/* Auto-generated from ウメキワークスDB (2026-02 〜 2026-05) */
export interface FundingRow { slug: string; date: string; company: string; round: string; amount: string; amountValue: number | null; sector: string; investors: string[]; }
export interface IpoRow { slug: string; ipoDate: string; company: string; lead: string; price: number | null; mcapOku: number | null; growthPct: number | null; }

export const fundingsRecent: FundingRow[] = [
  { slug: "umito", date: "2026-05-07", company: "UMITO", round: "", amount: "24.0億円", amountValue: 24.0, sector: "ホテル", investors: ["JAL", "Plan･Do･See", "Hongo Holdings"] },
  { slug: "r-001", date: "2026-04-30", company: "トグル", round: "C", amount: "33.4億円", amountValue: 33.4, sector: "不動産AI", investors: ["Axiom Asia Private Capital", "未来創生3号"] },
  { slug: "helical-fusion", date: "2026-04-28", company: "Helical Fusion", round: "B1", amount: "27.0億円", amountValue: 27.0, sector: "フュージョンエネルギー", investors: ["ニチアス", "長谷虎グループ", "瀬野汽船", "イークラウドNEXT", "鴻池運輸", "三谷産業"] },
  { slug: "pictoria", date: "2026-04-28", company: "Pictoria", round: "", amount: "3.3億円", amountValue: 3.3, sector: "VTuber関連事業・AIキャラクター", investors: ["キヤノンマーケティングジャパン", "みずほキャピタル", "GOLDEN EGG Ventures", "Skyland Venture"] },
  { slug: "r-004", date: "2026-04-28", company: "パトスロゴス", round: "B", amount: "31.0億円", amountValue: 31.0, sector: "大企業向けHR SaaS", investors: ["SBIインベストメント", "レオス・キャピタルパートナーズ"] },
  { slug: "qubitcore", date: "2026-04-27", company: "Qubitcore", round: "\u30b7\u30fc\u30c9", amount: "15.3億円", amountValue: 15.3, sector: "分散型量子コンピュータ", investors: ["SBIインベストメント", "Abies Ventureなど"] },
  { slug: "ystory", date: "2026-04-27", company: "YStory", round: "\u30d7\u30ecA", amount: "非公開", amountValue: null, sector: "更年期セルフケア", investors: ["京都大学イノベーションキャピタル", "あすか製薬CVC", "京都キャピタルパートナーズ", "栖峰投資ワークス", "NEXTBLUE", "ANRI"] },
  { slug: "flora", date: "2026-04-27", company: "Flora", round: "", amount: "2.3億円", amountValue: 2.3, sector: "フェムテック", investors: ["立命館ソーシャルインパクトファンド", "長瀬産業", "西京イノベーション"] },
  { slug: "cbcloud", date: "2026-04-24", company: "CBcloud", round: "", amount: "非公開", amountValue: null, sector: "配送プラットフォーム", investors: ["沖縄県内企業等14社・ファンド"] },
  { slug: "a1a", date: "2026-04-24", company: "A1A", round: "B", amount: "10.0億円", amountValue: 10.0, sector: "自動車業向け調達データ", investors: ["JAFCO", "i-nest capital", "イグニション・ポイント ベンチャーパートナーズ", "みずほキャピタル"] },
  { slug: "amidex", date: "2026-04-23", company: "amidex", round: "\u30d7\u30ecA", amount: "1.2億円", amountValue: 1.2, sector: "クリアインデックスシステム", investors: ["事業会社", "あわぎんイノベーション", "いよベンチャーファンド8号"] },
  { slug: "brave", date: "2026-04-22", company: "Brave", round: "E", amount: "80.0億円", amountValue: 80.0, sector: "Vtuber", investors: ["REALITY（グリー）", "クールジャパン", "みずほ銀行など"] },
  { slug: "mode", date: "2026-04-22", company: "MODE", round: "", amount: "9.7億円", amountValue: 9.7, sector: "建設・製造・物流現場向けIoT", investors: ["ソフトバンク", "ベイシス", "Sankyu-SBI イノベーションファンド1号"] },
  { slug: "prodrone", date: "2026-04-21", company: "Prodrone", round: "", amount: "非公開", amountValue: null, sector: "産業用ドローン", investors: ["東海研究開発1号"] },
  { slug: "ecommit", date: "2026-04-21", company: "ECOMMIT", round: "B", amount: "15.0億円", amountValue: 15.0, sector: "資源循環インフラ", investors: ["メルカリ", "シンプレクス・キャピタル・インベストメント", "ゆうちょアセットマネジメントなど"] },
  { slug: "r-015", date: "2026-04-20", company: "ストラウト", round: "\u30b7\u30fc\u30c9", amount: "1.5億円", amountValue: 1.5, sector: "陸上養殖", investors: ["ヤンマーベンチャーズ", "BORベンチャーファンド3号", "01Booster Capital", "ベータ・ベンチャーキャピタル"] },
  { slug: "kikuvi", date: "2026-04-20", company: "Kikuvi", round: "\u30b7\u30fc\u30c9", amount: "4.0億円", amountValue: 4.0, sector: "AIヒアリング・インタビューSaaS", investors: ["GCP", "Plug and Play Japan", "アニマルスピリッツ"] },
  { slug: "wota", date: "2026-04-17", company: "WOTA", round: "C", amount: "非公開", amountValue: null, sector: "水問題", investors: ["SMBC日興J-Ships"] },
  { slug: "r-018", date: "2026-04-16", company: "リプロネクスト", round: "\u30b7\u30fc\u30c9", amount: "1.2億円", amountValue: 1.2, sector: "対話型AIコンシェルジュ", investors: ["ジェネシア"] },
  { slug: "onestruction", date: "2026-04-16", company: "ONESTRUCTION", round: "", amount: "4.8億円", amountValue: 4.8, sector: "建設業向けBIMソフトウェア開発", investors: ["三井住友海上キャピタル", "地域と人とみらい CJS2号ファンド", "ちゅうぎんキャピタルパートナーズ", "アルバクロス"] },
  { slug: "mairu-tech", date: "2026-04-15", company: "mairu tech", round: "A", amount: "4.0億円", amountValue: 4.0, sector: "医療・福祉向けモビリティインフラ", investors: ["デライト・ベンチャーズ", "ANRI", "メドレー"] },
  { slug: "ballas", date: "2026-04-15", company: "BALLAS", round: "B", amount: "21.0億円", amountValue: 21.0, sector: "建設部材調達", investors: ["SMBC Edge", "ZVC", "JGC MIRAI Innovation Fund", "Sankyu-SBI イノベーションファンド", "大和ハウスベンチャーズ", "パーソルベンチャーパートナーズ", "SBIインベストメント", "京都キャピタルパートナーズ", "三井住友海上キャピタル"] },
  { slug: "almure", date: "2026-04-15", company: "Almure", round: "\u30b7\u30fc\u30c9", amount: "2.0億円", amountValue: 2.0, sector: "秘密計算", investors: ["ジェネシア・ベンチャーズ", "Dual Bridge Capital", "NEX-T Tokai Innovation Fund"] },
  { slug: "edgecortix", date: "2026-04-15", company: "EdgeCortix", round: "", amount: "非公開", amountValue: null, sector: "エッジAI（省電力AIプロセッサ）", investors: ["Axiro Semiconductor", "MPower Partners"] },
  { slug: "ludens-ai", date: "2026-04-14", company: "Ludens AI", round: "", amount: "6.0億円", amountValue: 6.0, sector: "AIコンパニオンロボット", investors: ["CWB Capital", "Linear Capital", "PKSHA Algorithm Fund"] },
  { slug: "r-025", date: "2026-04-14", company: "ポルティ", round: "\u30d7\u30ecA", amount: "1.5億円", amountValue: 1.5, sector: "空き家フリマアプリ", investors: ["みずほキャピタル", "NES", "インクルージョン・ジャパン", "90s1号"] },
  { slug: "loov", date: "2026-04-13", company: "LOOV", round: "A", amount: "8.4億円", amountValue: 8.4, sector: "プレゼン業務の自動化・資産化", investors: ["HAKOBUNE", "Archetype Ventures", "みずほキャピタル"] },
  { slug: "r-027", date: "2026-04-09", company: "ガクシー", round: "B1", amount: "4.25億円", amountValue: 4.25, sector: "奨学金プラットフォーム", investors: ["ニッセイ・キャピタル", "テラスカイベンチャーズ", "三菱UFJ信託銀行", "STATION Ai Central Japan 1号"] },
  { slug: "find", date: "2026-04-09", company: "find", round: "", amount: "非公開", amountValue: null, sector: "落とし物クラウド", investors: ["CDIBクロスボーダー・イノベーション・ファンド"] },
  { slug: "r-029", date: "2026-04-08", company: "リチェルカ", round: "A", amount: "17.0億円", amountValue: 17.0, sector: "Agentic ERP開発", investors: ["Angel Bridge", "ジェネシア・ベンチャーズ", "New Commerce Ventures"] },
  { slug: "mign", date: "2026-04-08", company: "mign", round: "", amount: "2.3億円", amountValue: 2.3, sector: "不動産・建設特化型AIエージェント", investors: ["Angel Bridge", "千葉道場", "サムライインキュベート", "アニマルスピリッツ"] },
  { slug: "new-space-intelligence", date: "2026-04-07", company: "New Space Intelligence", round: "A", amount: "4.3億円", amountValue: 4.3, sector: "衛生データ基盤", investors: ["パートナーズファンド", "YMFGキャピタル", "NTTドコモ・ベンチャーズ", "ゼンリンフューチャーパートナー", "JR東日本スタートアップ", "大晃", "epiST Ventures", "七十七キャピタル", "みずほキャピタル"] },
  { slug: "eeful", date: "2026-04-06", company: "EEFULホールディングス", round: "\u30d7\u30ecA", amount: "4.1億円", amountValue: 4.1, sector: "介護事業者向けクラウド", investors: ["GCP", "Dual Bridge Capital", "Identity Academy"] },
  { slug: "tensor-energy", date: "2026-04-02", company: "Tensor Energy", round: "A", amount: "9.5億円", amountValue: 9.5, sector: "再エネ発電", investors: ["GB", "GCP", "デライト・ベンチャーズ"] },
  { slug: "r-034", date: "2026-04-02", company: "パンフォーユー", round: "", amount: "非公開", amountValue: null, sector: "EC（パンサブスク）", investors: ["新韓－GB"] },
  { slug: "uniam", date: "2026-04-02", company: "uniam", round: "A", amount: "7.7億円", amountValue: 7.7, sector: "EC（猫フードグッズ）", investors: ["WPower Fund", "ANOBAKA", "クレストスキルパートナーズ"] },
  { slug: "r-036", date: "2026-04-01", company: "シンク・ネイチャー", round: "", amount: "3.8億円", amountValue: 3.8, sector: "生物多様性ビッグデータ", investors: ["ITV", "沖縄セルラー電話", "沖縄振興開発金融公庫", "ニッセイ・キャピタル", "三井住友トラスト・インベストメント", "SBI新生企業投資"] },
  { slug: "r-037", date: "2026-03-31", company: "クリスプ", round: "", amount: "37.0億円", amountValue: 37.0, sector: "カスタムサラダ", investors: ["ロッテ・ベンチャーズ", "OneCapital", "ソウ・ツー"] },
  { slug: "r-038", date: "2026-03-31", company: "マイクロニティ", round: "\u30b7\u30fc\u30c9", amount: "22.0億円", amountValue: 22.0, sector: "AI駆動型ソフトウェア事業承継", investors: ["VC"] },
  { slug: "syslea", date: "2026-03-31", company: "SYSLEA", round: "\u30b7\u30fc\u30c9", amount: "4.1億円", amountValue: 4.1, sector: "AIネイティブCRM", investors: ["ジャフコ"] },
  { slug: "booost", date: "2026-03-26", company: "Booost", round: "C", amount: "7.0億円", amountValue: 7.0, sector: "サステナビリティERP", investors: ["One Capital", "プロネクサス"] },
  { slug: "torihada", date: "2026-03-26", company: "TORIHADA", round: "", amount: "15.0億円", amountValue: 15.0, sector: "ショート動画マーケ", investors: ["ジャフコ", "Spiral Innovation Partners", "みずほキャピタル", "DGりそな", "りそなキャピタ", "Hakuhodo DY ONE", "オールアバウト", "ブランジスタ", "JR西日本イノベーションズ", "YMFGキャピタル"] },
  { slug: "boost-health", date: "2026-03-26", company: "Boost Health", round: "", amount: "1.5億円", amountValue: 1.5, sector: "HR（タレントサクセス）", investors: ["ジェネシア・ベンチャーズ", "WPower Fund"] },
  { slug: "gaia", date: "2026-03-25", company: "Gaia", round: "", amount: "4.0億円", amountValue: 4.0, sector: "AIネイティブファンド", investors: ["イオレ", "ベンチャーラボイノベーション"] },
  { slug: "winebank", date: "2026-03-24", company: "WineBank", round: "A", amount: "1.6億円", amountValue: 1.6, sector: "ワイン売買・管理プラットフォーム", investors: ["HIRAC FUND2号", "Private BANK", "ベクトル", "寺田倉庫"] },
  { slug: "zevero", date: "2026-03-24", company: "Zevero", round: "", amount: "11.0億円", amountValue: 11.0, sector: "カーボンマネジメントプラットフォーム", investors: ["Spiral Capital", "Gazelle Capital", "Deep30など"] },
  { slug: "ugo", date: "2026-03-19", company: "ugo", round: "", amount: "非公開", amountValue: null, sector: "DXロボット", investors: ["JR東日本スタートアップ"] },
  { slug: "orbital-lasers", date: "2026-03-19", company: "Orbital Lasers", round: "A", amount: "30.2億円", amountValue: 30.2, sector: "宇宙用レーザー技術", investors: ["スパークス", "JICVGI", "慶應イノベーション・イニシアティブ", "Angel Bridge", "大阪大学ベンチャーキャピタル", "三菱UFJキャピタル", "みずほキャピタル", "SMBCベンチャーキャピタル", "スカパーJCAST"] },
  { slug: "free-standard", date: "2026-03-17", company: "Free Standard", round: "A", amount: "非公開", amountValue: null, sector: "リコマースオペレーティング", investors: ["KURONEKO Innovation Fund", "D4V", "BRICKS FUND TOKYO", "三井不動産＆イノベーションファンド"] },
  { slug: "r-049", date: "2026-03-17", company: "ライトライト", round: "A", amount: "3.4億円", amountValue: 3.4, sector: "オープンネーム事業承継プラットフォーム", investors: ["HIRAC FUND", "ひだしんイノベーションパートナーズ", "なんぎんキャピタル", "三星グループ"] },
  { slug: "grafto", date: "2026-03-17", company: "grafto", round: "\u30b7\u30fc\u30c9", amount: "1.0億円", amountValue: 1.0, sector: "韓国トレンドメディア", investors: ["mint", "ANRI"] },
  { slug: "lobbyai", date: "2026-03-17", company: "LobbyAI", round: "\u30d7\u30ecA", amount: "3.0億円", amountValue: 3.0, sector: "公共政策情報分析", investors: ["ファーストライト・キャピタル", "PKSHA Algorithm Fund", "三菱UFJキャピタル"] },
  { slug: "surf-music", date: "2026-03-16", company: "SURF Music", round: "\u30d7\u30ecA", amount: "630万ドル", amountValue: null, sector: "クリエイターエコノミー型音楽", investors: ["YG Plus Inc", "エニグモ", "agehasprings", "レインボーエンタテインメント", "ヒップランドミュージックコーポレーション"] },
  { slug: "andeco", date: "2026-03-13", company: "Andeco", round: "", amount: "1.5億円", amountValue: 1.5, sector: "スマートビルディング", investors: ["CVC"] },
  { slug: "the-rich", date: "2026-03-12", company: "THE RICH", round: "", amount: "8.0億円", amountValue: 8.0, sector: "D2C（シャンプー）", investors: ["シータ・タイムズ・ベンチャーズ"] },
  { slug: "enbase", date: "2026-03-11", company: "ENBASE", round: "", amount: "3.5億円", amountValue: 3.5, sector: "在宅ケア向け音声AIアシスタント", investors: ["One Capital", "KUSABI 1号"] },
  { slug: "r-056", date: "2026-03-11", company: "将来宇宙輸送システム", round: "", amount: "32.0億円", amountValue: 32.0, sector: "人工衛星打上げ用ロケット", investors: ["インキュベイト", "BDV", "愛知産業", "おぞら企業投資", "アニマルスピリッツ", "フォースタートアップスキャピタル", "北洋銀行", "ミッドタウン・フロンティア・ファンド", "Angel Bridge", "JALエンジニアリング", "NES", "XTech Ventures"] },
  { slug: "lenzo", date: "2026-03-11", company: "LENZO", round: "\u30b7\u30fc\u30c9", amount: "5.0億円", amountValue: 5.0, sector: "半導体", investors: ["インキュベイト", "Sony Innovation Fund", "三菱UFJキャピタル"] },
  { slug: "solafune", date: "2026-03-10", company: "Solafune", round: "A", amount: "50.0億円", amountValue: 50.0, sector: "衛生データ地理空間解析技術開発", investors: ["GCP", "Boost Capital", "Rice Capital", "三菱UFJキャピタル", "みずほキャピタル", "りそなキャピタル", "千葉道場ファンド"] },
  { slug: "asterminds", date: "2026-03-10", company: "Asterminds", round: "", amount: "1.1億円", amountValue: 1.1, sector: "AIヒアリングエージェント", investors: ["デライト・ベンチャーズ", "DNX Ventures"] },
  { slug: "r-060", date: "2026-03-05", company: "ドーガン", round: "", amount: "3.1億円", amountValue: 3.1, sector: "地域特化型投資ファンド", investors: ["25社"] },
  { slug: "r-061", date: "2026-03-05", company: "リデルタ", round: "", amount: "1.2億円", amountValue: 1.2, sector: "東南アジア特化M&Aデータベース", investors: ["ANRI", "EV", "G-STARTUP"] },
  { slug: "r-062", date: "2026-03-04", company: "トイポ", round: "", amount: "2.8億円", amountValue: 2.8, sector: "行動データプラットフォーム", investors: ["CCIA", "FFGベンチャービジネスパートナーズ", "GxPartners", "ジャフコ", "GCP"] },
  { slug: "spiralai", date: "2026-03-04", company: "SpiralAI", round: "", amount: "非公開", amountValue: null, sector: "LLM", investors: ["Spiral Capital", "コーエーテクモキャピタル", "Scrum Ventures"] },
  { slug: "r-064", date: "2026-03-03", company: "カウシェ", round: "", amount: "非公開", amountValue: null, sector: "EC", investors: ["DeNA"] },
  { slug: "r-065", date: "2026-03-02", company: "衛星データサービス企画", round: "", amount: "非公開", amountValue: null, sector: "衛星データ活用", investors: ["三菱電機", "三菱UFJ銀行", "ID&Eホールディングス", "国際航業株式会社", "ゼンリン"] },
  { slug: "custa", date: "2026-03-02", company: "CUSTA", round: "A", amount: "6.5億円", amountValue: 6.5, sector: "カスタマイズ製品受発注", investors: ["デライト・ベンチャーズ", "GB"] },
  { slug: "r-067", date: "2026-02-27", company: "レコテック", round: "", amount: "非公開", amountValue: null, sector: "資源循環データプラットフォーム", investors: ["マーキュリア・サプライチェーンファンド", "かんぽNEXTパートナーズ", "三菱UFJキャピタル", "みずほキャピタル", "ヒューリックスタートアップ", "京都キャピタルパートナーズ"] },
  { slug: "all-in", date: "2026-02-27", company: "ALL in", round: "", amount: "8.0億円", amountValue: 8.0, sector: "ライフエンディング", investors: ["Dual Bridge Capital", "Tycoon Capital", "静岡キャピタル", "コロプラネクスト", "ごうぎんキャピタル"] },
  { slug: "jpyc", date: "2026-02-27", company: "JPYC", round: "B", amount: "17.6億円", amountValue: 17.6, sector: "日本円ステーブルコイン", investors: ["アステリア", "QR2号", "JR西日本イノベーションズ", "directX Ventures1号", "ちゅうぎんインフィニティファンド3号", "TNBI1号", "TMキャピタル", "テクミラ", "HEROZ", "bitFlyer Holdings", "fundnote", "FINOLAB1号", "明治安田未来", "両備システムズイノベーション"] },
  { slug: "esree-energy", date: "2026-02-26", company: "ESREE Energy", round: "", amount: "非公開", amountValue: null, sector: "蓄熱技術", investors: ["ユナイテッド", "デジタルグリッド", "ReGACY Innovation Group"] },
  { slug: "x-mile", date: "2026-02-25", company: "X Mile", round: "", amount: "非公開", amountValue: null, sector: "ノンデスク産業向けSaaS・HR", investors: ["セイノーHD", "NXグループ", "日本郵政キャピタル"] },
  { slug: "r-072", date: "2026-02-25", company: "マチルダ", round: "B", amount: "4.1億円", amountValue: 4.1, sector: "家庭料理テイクアウト", investors: ["ロッテベンチャーズ・ジャパン", "Future Food Fund", "三菱UFJキャピタル", "POLA ORBIS CAPITAL", "オリエンタルランド・イノベーションズ"] },
  { slug: "yamastro", date: "2026-02-25", company: "YAMASTRO", round: "\u30b7\u30fc\u30c9", amount: "1.0億円", amountValue: 1.0, sector: "金属部品製造", investors: ["インキュベイト"] },
  { slug: "bluefield-energy", date: "2026-02-25", company: "Bluefield Energy", round: "\u30b7\u30fc\u30c9", amount: "6.6億円", amountValue: 6.6, sector: "電力アグリゲーション", investors: ["XTech Ventures", "SMBCベンチャーキャピタル", "三菱UFJキャピタル", "みずほキャピタル", "ほくほくキャピタル", "ごうぎんキャピタル", "肥銀キャピタル"] },
  { slug: "r-075", date: "2026-02-25", company: "ムービーズ", round: "\u30b7\u30fc\u30c9", amount: "2.0億円", amountValue: 2.0, sector: "ロボタクシー", investors: ["Partners Fund"] },
  { slug: "anique", date: "2026-02-24", company: "Anique", round: "B", amount: "13.0億円", amountValue: 13.0, sector: "エンタメIP化", investors: ["GB9", "TAKANAWA GATEWAY地球益投資", "キャノンマーケ", "丸井"] },
  { slug: "r-077", date: "2026-02-20", company: "クラシテク", round: "A", amount: "非公開", amountValue: null, sector: "医療・介護業界特化型AIエージェント", investors: ["Rice Capital"] },
  { slug: "r-078", date: "2026-02-19", company: "アラカン", round: "C", amount: "非公開", amountValue: null, sector: "自動車フリマ", investors: ["ジャフコ", "KeePer技研"] },
  { slug: "sotas", date: "2026-02-18", company: "SOTAS", round: "A", amount: "10.0億円", amountValue: 10.0, sector: "化学産業向け情報基盤提供", investors: ["GCP", "ツカサペトコ", "弘栄貿易", "ALL STAR SAAS FUND", "Archetype Ventures", "サムライインキュベート", "デライト・ベンチャーズ", "三菱UFJキャピタル"] },
  { slug: "suicte", date: "2026-02-18", company: "SUiCTE", round: "\u30b7\u30fc\u30c9", amount: "1.4億円", amountValue: 1.4, sector: "宇宙衛星用半導体イメージセンサ・カメラ", investors: ["クオンタムリープベンチャーズ", "インキュベイト"] },
  { slug: "yuimedi", date: "2026-02-18", company: "Yuimedi", round: "", amount: "4.0億円", amountValue: 4.0, sector: "医療データ利活用インフラ", investors: ["DG Daiwa Ventures", "三井住友信託銀行", "HearstLab", "SMBCベンチャーキャピタル", "千葉道場", "インキュベイトファンド", "D4V"] },
  { slug: "not-a-hotel", date: "2026-02-17", company: "NOT A HOTEL", round: "C", amount: "26.0億円", amountValue: 26.0, sector: "シェア別荘", investors: ["Minerva Growth Partners", "セコイア", "Hillhouse Investment Management", "SuMi TRUSTイノベーション2号ファンド"] },
  { slug: "a-wave", date: "2026-02-17", company: "A-wave", round: "B", amount: "5.4億円", amountValue: 5.4, sector: "心不全患者向け在宅モニタリング", investors: ["MedVenture Partners", "かんぽNEXTパートナーズ", "大阪大学ベンチャーキャピタル", "三菱UFJキャピタル", "ディープコア・池田泉州キャピタル", "GB-島津製作所", "ギガ・システム"] },
  { slug: "smart-craft", date: "2026-02-17", company: "Smart Craft", round: "\u30d7\u30ecA", amount: "1.8億円", amountValue: 1.8, sector: "クラウド製造実行システム", investors: ["三井住友海上キャピタル", "三菱UFJキャピタル"] },
  { slug: "payn", date: "2026-02-16", company: "Payn", round: "A", amount: "2.5億円", amountValue: 2.5, sector: "キャンセル料請求・回収ツール", investors: ["アポロ・キャピタル", "NCBベンチャーキャピタル", "Carbon Ventures", "DE-SIGNキャピタル"] },
  { slug: "ecbo", date: "2026-02-13", company: "ecbo", round: "", amount: "非公開", amountValue: null, sector: "荷物預かり", investors: ["クールジャパン", "ダイセーホールディングス", "DE-SIGNキャピタル"] },
  { slug: "yoake-entertainment", date: "2026-02-13", company: "YOAKE entertainment", round: "", amount: "5.0億円", amountValue: 5.0, sector: "オンチェーンエンタメ", investors: ["Sony Innovation Fund"] },
  { slug: "r-088", date: "2026-02-13", company: "あかり保証", round: "", amount: "非公開", amountValue: null, sector: "高齢者等終身サポート", investors: ["SMBCベンチャーキャピタル", "みずほキャピタル", "ミライドア", "インキュベイト"] },
  { slug: "minto", date: "2026-02-13", company: "Minto", round: "", amount: "5.0億円", amountValue: 5.0, sector: "IP", investors: ["テレビ東京"] },
  { slug: "r-090", date: "2026-02-12", company: "ゴーレム", round: "A", amount: "8.0億円", amountValue: 8.0, sector: "建設データプラットフォーム", investors: ["ANRI", "清水建設", "竹中工務店", "阪急阪神不動産", "MIRAITRONC"] },
  { slug: "piazza", date: "2026-02-12", company: "PIAZZA", round: "B", amount: "2.6億円", amountValue: 2.6, sector: "まちづくりプラットフォーム", investors: ["ブルーインキュベーション", "西武しんきんキャピタル", "信金キャピタル", "博報堂"] },
  { slug: "healthree", date: "2026-02-12", company: "HEALTHREE", round: "A", amount: "非公開", amountValue: null, sector: "ヘルスケアゲームアプリ", investors: ["東京ウェルネスインパクトファンド", "かんぽNEXTパートナーズ", "越境"] },
  { slug: "shizuku-ai", date: "2026-02-12", company: "Shizuku AI", round: "\u30b7\u30fc\u30c9", amount: "非公開", amountValue: null, sector: "AIキャラ", investors: ["a16z"] },
  { slug: "r-094", date: "2026-02-09", company: "クオリィ", round: "A", amount: "18.0億円", amountValue: 18.0, sector: "マイクロサージャリー支援ロボット", investors: ["ファストトラックイニシアティブ", "MedVenture Partners", "ソニー", "DBJ"] },
  { slug: "r-095", date: "2026-02-04", company: "ディッシュウィル", round: "\u30b7\u30fc\u30c9", amount: "2.0億円", amountValue: 2.0, sector: "アグリ・フードテック", investors: ["デライト・ベンチャーズ", "SGgrow Pte"] },
  { slug: "commercex", date: "2026-02-03", company: "CommerceX", round: "A", amount: "17.3億円", amountValue: 17.3, sector: "ブランドM&Aロールアップ", investors: ["ニッセイ・キャピタル", "DUAL BRIDGE CAPITAL", "New Commerce Ventures", "三菱UFJキャピタル"] },
  { slug: "valance", date: "2026-02-02", company: "VALANCE", round: "\u30b7\u30fc\u30c9", amount: "2.7億円", amountValue: 2.7, sector: "AI駆動型Headless SCM", investors: ["デライト・ベンチャーズ", "SMBC Edge", "三菱UFJキャピタル"] },
  { slug: "feidias", date: "2026-02-02", company: "FEIDIAS", round: "", amount: "2.0億円", amountValue: 2.0, sector: "AI", investors: ["国内ファミリーオフィスなど"] },
];

export const iposRecent: IpoRow[] = [
  { slug: "r-1000", ipoDate: "2026-03-02", company: "雛", lead: "SMBC日興", price: null, mcapOku: null, growthPct: null },
  { slug: "r-1001", ipoDate: "2026-04-23", company: "犬猫生活", lead: "SBI", price: 2990, mcapOku: 78.22, growthPct: 53.1 },
  { slug: "squeeze", ipoDate: "2026-04-22", company: "SQUEEZE", lead: "SBI", price: null, mcapOku: 100.17, growthPct: 31.1 },
  { slug: "r-1003", ipoDate: "2026-04-21", company: "バトンズ", lead: "大和", price: null, mcapOku: 30.51, growthPct: 46.7 },
  { slug: "r-1004", ipoDate: "2026-03-27", company: "セイワ", lead: "SBI", price: null, mcapOku: 235.06, growthPct: 0.1 },
  { slug: "r-1005", ipoDate: "2026-03-25", company: "ベーシック", lead: "岡三！！！", price: null, mcapOku: 58.15, growthPct: 25.0 },
];
